### ISSUE TITLE
メールアドレスで登録の流れを実装する

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#72]
メールアドレスで登録の流れを実装する

register_mail 画面、 register_vertify画面、register_user画面、learning community search画面

<img width="801" alt="スクリーンショット 2023-10-01 18 21 48" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/828cb2aa-7303-4f52-afc0-5817d44ae698">

### TODO: 

- [x] 登録メールのエラーハンドリング → #138 で対応済
- [x] メール認証する → 実装されていた。対応済。
- [x] 認証メールを再送する → 再送ボタン見たら実装されていた。対応済。
- [x] 名前を登録する → #123 まち、別 issue に切り出す。

- [x] あなたの経験、得意なことを教えてください！では
  - オススメハッシュタグを最大4行程度表示（スクロールはさせない）
  - 選んだタグはプロフィールに反映（#文字の形式）
  - 検索すると既知のハッシュタグでヒットするものを表示する
  → 別途 issue にした #137 

_Originally posted by @ken-ty in https://github.com/Mayumi-Nakabayashi/withTone/issues/59#issuecomment-1742018878_

**Comment by ken-ty** [comment]
Firebaseのメールの認証は認証コードではなく、メールリンク認証。
https://zenn.dev/satjopg/articles/c85a039cf8afe2#%E3%83%95%E3%83%AD%E3%83%BC
デザインを見直す必要がある。

ただし、Figma をすぐ直すより、一旦メールリンク認証で開発しちゃってから、動作に合わせて Figma を修正する方が良さそう。

**Comment by ken-ty** [comment]
認証メールを日本語にした。

<img width="1172" alt="スクリーンショット 2023-11-01 15 23 04" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/398362c2-2496-426f-a1b2-336c5cb6b808">

**Comment by ken-ty** [comment]
現状、うしさんが作ってくれた送信後画面に遷移する。
![flutter_01](https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/f2b374cf-497d-42eb-bd33-a4e00f86c2b9)

**Comment by ken-ty** [comment]
名前を作成ページを追加する必要がある。

**Comment by ken-ty** [comment]
あなたの経験、得意なことを教えてください！　は後回しで良さそう。
別途 issue を立てて対応する。

**Comment by ken-ty** [comment]
名前を作成 機能実装
